CELEBRITY_LIST = [

# Acteurs/Actrices
"theestallion",
"zendaya",
"therock",
"vindiesel",
"scarlettjohansson",
"chrishemsworth",
"jenniferlawrence",
"robertpattinson",
"blakelively",
"ryangosling",
"tomholland2013",
"annehathaway",
"leonardodicaprio",
"willsmith",
"angelababyct",
"priyankachopra",
"deepikapadukone",
"aliaabhatt",
"hrithikroshan",
"salmankhan",

# Chanteurs/Chanteuses
"beyonce",
"justinbieber",
"selenagomez",
"arianagrande",
"taylorswift",
"rihanna",
"kanyewest",
"ladygaga",
"adele",
"brunomars",
"justinbieber",
"katyperry",
"onedirection",
"shakira",
"chrisbrown",
"demilovato",
"jlo",
"usher",
"rihanna",
"elvispresley",

# Sportifs
"cristiano",
"leomessi",
"serenawilliams",
"neymarjr",
"stephencurry30",
"michaeljordan",
"ronaldinho",
"simonebiles",
"usainbolt",
"alexmorgan13",
"lionelmessi",
"virat.kohli",
"neymarjr",
"msdhoni",
"ronaldinho",
"serenawilliams",
"stephencurry30",
"alexmorgan13",
"phelpsmichael",

# Autres Personnalités Publiques
"kimkardashian",
"kyliejenner",
"kendalljenner",
"gigihadid",
"khloekardashian",
"kourtneykardash",
"oprah",
"barackobama",
"elonmusk",
"theresa_may",
"kimkardashian",
"kyliejenner",
"kendalljenner",
"gigihadid",
"khloekardashian",
"kourtneykardash",
"oprah",
"barackobama",
"elonmusk",
"theresa_may",

# Noms d'utilisateur créatifs
"fashion_inspiration",
"foodiegram",
"travelholic",
"booklover",
"fitfam",
"makeuplover",
"sneakerhead",
"artcollector",
"petlover",
"entrepreneur",
"foodie",
"traveler",
"photographer",
"artist",
"designer",
"writer",
"musician",
"dancer",
"athlete",
"scientist",

# ... (suite de la liste)

# Personnalités Publiques Françaises
"karimbenzema",
"kylianmbappe",
"paulpogba",
"ngolokante",
"antoinegriezmann",
"zinedinezidane",
"martinemartinpourtous",
"louaneofficiel",
"sophie_marceau",
"jeanreno",
"yannbarthes",
"omar_sy",

# Humoristes
"kev_adams",
"florence_foresti",
"b Gad Elmaleh",
"jameldebbouze",
"anne_roumanoff",
"gaspardprotzer",

# Influenceurs
"marie_autrefois",
"massimo_giovannini",
"le_monde_selon_caro",
"mybetterself",
"sananas2607",
"joyca",

# Chefs cuisiniers
"cyril_lignac",
"philippe_etchebest",
"helenedarroze",
"anne_sophie_pic",
"yanncouvreur",

# Journalistes
"apolina_morin",
"hugodelamotte",
"lea_salame",
"anneclairecoudray",
"najat_vallaud_belkacem",

# Politiques
"emmanuelmacron",
"jeancastelex",
"gerald_darmanin",
"anne_hidalgo",
"marine_le_pen",

# Sportifs Français
"martina_navarro_leonard",
"clarisse_agbegnenou"]